# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
 
resources:
  repositories:
  - repository: rp2
    type: github
    endpoint: github.com_dmittal01
    name: dmittal01/mappingcheck
    ref: main
    trigger:
    - main
  - repository: rp3
    type: git
    name: rp3
    ref: main
    trigger:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: rp2
- checkout: rp3

